[package]
name = "axon"
version = "0.1.0"
authors = ["Jonathan Schleu√üer <paradoxspiral@riseup.net>"]

[dependencies]
chrono = "0.4"
crossbeam = "0.3"
futures = "0.1"
humansize = "1"
itertools = "0.7"
lazy_static = "1"
parking_lot = "0.5"
synapse-rpc = "0.1"
serde = "1"
serde_json = "1"
termion = "1"
tokio-core = "0.1"
websocket = "0.20"
unicode-segmentation = "1"
unicode-width = "0.1"
url = "1"

slog = { version = "2", optional = true }
slog-term = { version = "2", optional = true }
slog-async = { version = "2", optional = true }

[features]
dbg = ["slog", "slog-term", "slog-async"] # Note that your server & pass will be in the debug log!
